### ISSUE TITLE
How to unzip the OCFBench-nuScenes.sqf file in huggingface?

### ISSUE THREAD

**Issue by synsin0** [ai4ce/Occ4cast#5]
Thanks for your work on Occ4D. My question is as title.

**Comment by synsin0** [comment]
I attempt to mount to ubuntu system but report error: mount failed. mount not permitted. May you provide an example of mounting command?

**Comment by Gaaaavin** [comment]
You will need sudo access to directly mount the .sqf file to your system.
If you are using singularity containers, you can mount the .sqf file using the `--overlay` flag when launching the container.
Otherwise, you will need to extract the file with `unsquashfs` command and then access the unzipped folder.
